/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf 
Author: Nikitos & 3130 (https://sketchfab.com/vrcityphoto)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/tokyo-night-9a50456b41ec4b17b870883d75c6b184
Title: TOKYO NIGHT
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function TokyoScene(props) {
  const { nodes, materials } = useGLTF('/tokyo_night.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 39.581, 48.562]} rotation={[-Math.PI, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials['JAPAN_NIGHT.1001']} />
        <mesh geometry={nodes.Object_3.geometry} material={materials['JAPAN_NIGHT.1001']} />
        <mesh geometry={nodes.Object_4.geometry} material={materials['JAPAN_NIGHT.1001']} />
        <mesh geometry={nodes.Object_5.geometry} material={materials['JAPAN_NIGHT.1001']} />
        <mesh geometry={nodes.Object_6.geometry} material={materials['JAPAN_NIGHT.1002']} />
        <mesh geometry={nodes.Object_7.geometry} material={materials['JAPAN_NIGHT.1002']} />
        <mesh geometry={nodes.Object_8.geometry} material={materials['JAPAN_NIGHT.1002']} />
        <mesh geometry={nodes.Object_9.geometry} material={materials['JAPAN_NIGHT.1002']} />
        <mesh geometry={nodes.Object_10.geometry} material={materials['JAPAN_NIGHT.1003']} />
        <mesh geometry={nodes.Object_11.geometry} material={materials['JAPAN_NIGHT.1003']} />
        <mesh geometry={nodes.Object_12.geometry} material={materials['JAPAN_NIGHT.1003']} />
        <mesh geometry={nodes.Object_13.geometry} material={materials['JAPAN_NIGHT.1003']} />
      </group>
    </group>
  )
}

useGLTF.preload('/tokyo_night.glb')
